import "@testing-library/jest-dom";
import React from "react";
import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import SeriesMappingSummaryCard from "./seriesMappingSummaryCard";
import { SeriesMappingUtils } from "@/utils/seriesMappingUtils";
import eventbus from "@/api/eventbus";
import { SETTINGS_NAVIGATE } from "@/data/settingsNav";

jest.mock("@/utils/seriesMappingUtils");

const mockGetMappingStats = SeriesMappingUtils.getMappingStats as jest.Mock;
const mockCleanExpiredMappings = SeriesMappingUtils.cleanExpiredMappings as jest.Mock;

describe("SeriesMappingSummaryCard", () => {
  beforeEach(() => {
    jest.clearAllMocks();
    mockGetMappingStats.mockResolvedValue({ total: 12, byPlatform: {}, userConfirmed: 10, autoGenerated: 2, expiringSoon: 3 });
    mockCleanExpiredMappings.mockResolvedValue(3);
  });

  test("shows total and expiring/expired counts once stats load", async () => {
    render(<SeriesMappingSummaryCard />);
    await waitFor(() => expect(screen.getByText("12")).toBeInTheDocument());
    expect(screen.getByText("3")).toBeInTheDocument();
  });

  test("clear expired mappings button calls cleanExpiredMappings and refreshes the stats", async () => {
    render(<SeriesMappingSummaryCard />);
    await waitFor(() => expect(screen.getByTestId("clear-expired-mappings-button")).not.toBeDisabled());

    fireEvent.click(screen.getByTestId("clear-expired-mappings-button"));

    await waitFor(() => expect(mockCleanExpiredMappings).toHaveBeenCalled());
    expect(mockGetMappingStats).toHaveBeenCalledTimes(2);
  });

  test("clear expired mappings button is disabled when nothing is expiring", async () => {
    mockGetMappingStats.mockResolvedValue({ total: 5, byPlatform: {}, userConfirmed: 5, autoGenerated: 0, expiringSoon: 0 });
    render(<SeriesMappingSummaryCard />);
    await waitFor(() => expect(screen.getByTestId("clear-expired-mappings-button")).toBeDisabled());
  });

  test("the manage link publishes a SETTINGS_NAVIGATE event for the mappings tab", async () => {
    const handler = jest.fn();
    eventbus.subscribe(SETTINGS_NAVIGATE, handler);

    render(<SeriesMappingSummaryCard />);
    await waitFor(() => expect(screen.getByTestId("navigate-to-mappings-button")).toBeInTheDocument());
    fireEvent.click(screen.getByTestId("navigate-to-mappings-button"));

    expect(handler).toHaveBeenCalledWith(expect.objectContaining({ value: { id: "mappings" } }));
    eventbus.unsubscribe(SETTINGS_NAVIGATE, handler);
  });
});
