name: Build and Test
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Install dependencies
        run: npm install

      - name: Test coverage
        run: npm test -- --coverage

      - name: Extract coverage percentage
        id: extract-coverage
        run: |
          COVERAGE=$(grep 'All files' ./coverage/lcov.info | awk '{print $NF}')
          echo "::set-output name=coverage::$COVERAGE"

      - name: Add comment to PR
        uses: actions/github-script@v5
        with:
          script: |
            const issue_number = context.issue.number;
            const body = `Code coverage is ${{ steps.extract-coverage.outputs.coverage }}`;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: body
            });